[package]
edition = "2024"
name = "runtime"

[dependencies]
common = { path = "../common" }
dsl = { path = "../dsl" }
generated = { path = "../generated" }
tokio = { workspace = true }
slab = "0.4"

[build-dependencies]
common = { path = "../common" }
dsl = { path = "../dsl" }
